@extends('layouts.layout')

@include('components.header')
@include('components.hero')
@include('components.about')
@include('components.stats')
@include('components.client')
@include('components.service')
@include('components.portofolio')
@include('components.gallery')
@include('components.team')
@include('components.testimonial')
@include('components.contact')
@include('components.footer')