@extends('dashboard')

@include('components.budgeReport')
@include('components.customerCard')
@include('components.recentActivityCard')
@include('components.recentSales')
@include('components.reportCard')
@include('components.revenueCard')
@include('components.salesCard')
@include('components.topSelling')
@include('components.updateTraffic')
@include('components.websiteTraffic')